version: '3.8'

services:
    db:
        container_name: mysql-db
        image: mysql:8.0.36
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - ./.env
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}


